# Generated by Django 2.1.4 on 2019-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksite', '0004_auto_20181211_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
