# Generated by Django 2.1.4 on 2019-01-24 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banksite', '0005_auto_20190124_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Payment',
        ),
    ]
